version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong@Password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - appnet
    volumes:
      - sqlserver_data:/var/opt/mssql

  api:
    build:
      context: ..
      dockerfile: Config/Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - appnet
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ../src:/app/src

volumes:
  sqlserver_data:

networks:
  appnet:
    driver: bridge
